name: Pull request K8s integration tests

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read

jobs:
  test:
    permissions:
      # Required for codecov
      checks: write
      pull-requests: write
      # Required for uploading artifacts
      actions: write
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.25' ]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          cache: 'false'
          go-version: ${{ matrix.go }}
      - name: Clean up disk space
        run: |
          docker system prune -af
          docker volume prune -f
      - name: Run integration tests
        run: make docker-generate integration-test-k8s
        timeout-minutes: 60
      - name: Upload integration test logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: K8s test Logs
          path: |
            testoutput/*.log
            testoutput/kind
      - name: Report coverage
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./testoutput/itest-covdata.txt
          flags: k8s-integration-test-${{ github.run_number }}-${{ matrix.id }}
