name: PR OATS test

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
    branches: ["main", "release-*"]

permissions:
  contents: read

jobs:
  test-matrix:
    name: "Build oats matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: build matrix
        id: build-matrix
        run: |
          echo -n "matrix=" >> $GITHUB_OUTPUT
          make oats-integration-test-matrix-json >> $GITHUB_OUTPUT

  test:
    name: ${{ matrix.basename }}
    needs: test-matrix
    permissions:
      # Required for codecov
      checks: write
      pull-requests: write
      # Required for uploading artifacts
      actions: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.25"
          cache: false

      - name: Run oats tests
        env:
          MATRIX_BASENAME: ${{ matrix.basename }}
        run: make oats-test-$MATRIX_BASENAME

      - name: Upload oats test logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: Oats test logs - ${{ matrix.basename }}
          path: test/oats/${{ matrix.basename }}/build/*

      - name: Process coverage data
        run: make itest-coverage-data

      - name: Report coverage
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./testoutput/itest-covdata.txt
          flags: oats-test
